name: safety_observation
description: Offline safety observation application for Android.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.17
  sqflite: 2.4.2+1
  path_provider: 2.1.6
  path: 1.9.1
  image_picker: 1.2.3
  file_picker: 13.1.0
  archive: 4.0.9
  pdf: 3.12.0
  printing: 5.14.3
  share_plus: 13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home/
    - assets/icons/observation_type/
    - assets/icons/basic_information/
    - assets/icons/employee_information/
    - assets/icons/observed_event/
    - assets/icons/potential_hazard/
    - assets/icons/action_taken/
    - assets/icons/safety_categories/
    - assets/icons/safe_unsafe_actions/
    - assets/icons/risk_ranking/
    - assets/icons/supervisor_notification/
    - assets/icons/attachments/
    - assets/icons/review_and_save/
    - assets/icons/reports_history/
    - assets/icons/report_details/
    - assets/fonts/
