name: safety_observation
description: Offline safety observation application for Android.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home/
    - assets/icons/observation_type/
    - assets/icons/basic_information/
    - assets/icons/employee_information/
    - assets/icons/observed_event/
    - assets/icons/potential_hazard/
    - assets/icons/action_taken/
