/// English copy is centralized so localization can be added without editing
/// individual widgets. This app has no server sync in version one.
abstract final class AppStrings {
  static const appName = 'Safety Observation';
  static const shortAppName = 'Safety Obs';
  static const subtitle = 'STOP CARD SYSTEM';
  static const offline = 'Offline';
  static const newObservation = 'New Observation';
  static const newObservationDescription =
      'File a real-time safety report or Stop Card instantly.';
  static const myReports = 'My Reports';
  static const myReportsDescription = 'View reports saved on this device';
  static const importReport = 'Import Report';
  static const importReportDescription = 'Import a .safety file';
  static const reportStatus = 'Report Status';
  static const activeSiteNotSet = 'NO ACTIVE SITE';
  static const drafts = 'Drafts';
  static const pending = 'Pending';
  static const completed = 'Completed';
  static const recent = 'Recent';
  static const offlineNotice =
      'Reports are saved on this device. Export a backup regularly to protect your data.';
  static const featurePending = 'This feature is being implemented.';
  static const selectObservationType = 'Select Observation Type';
  static const stepOneOfTen = 'Step 1 of 10';
  static const nearMiss = 'Near Miss';
  static const nearMissDescription =
      'An unplanned event that did not result in injury, illness, or damage.';
  static const tofs = 'TOFS';
  static const tofsDescription =
      'Time Out For Safety — brief discussion to address workplace safety.';
  static const hazardId = 'Hazard I.D.';
  static const hazardIdDescription =
      'Identification of potential sources of harm or adverse health effects.';
  static const stopCard = 'Stop Card';
  static const stopCardDescription =
      'Immediate authority to halt work due to unsafe conditions or actions.';
  static const stopCardCategory = 'Stop Card Category';
  static const positive = 'Positive';
  static const unsafeCorrective = 'Unsafe / Corrective';
  static const continueToForm = 'Continue to Form';
  static const selectCategory = 'Select a Stop Card category to continue.';
  static const basicInfo = 'Basic Info';
  static const stepTwoOfTen = 'Step 2 of 10';
  static const autoRecordedNotice =
      'Date, time, and report ID are recorded automatically.';
  static const reportId = 'Report ID';
  static const autoGenerated = 'Auto-generated';
  static const dateRecorded = 'Date Recorded';
  static const time = 'Time';
  static const area = 'Area';
  static const requiredAreaLabel = 'AREA *';
  static const selectArea = 'Select Area';
  static const enterArea = 'Enter work area';
  static const areaRequired = 'Select an area before continuing.';
  static const continueLabel = 'Continue';
  static const cancel = 'Cancel';
  static const save = 'Save';
  static String stepOfTen(int step) => 'Step $step of 10';
  static const employeeInfo = 'Employee Info';
  static const employeeInfoNotice = 'Enter the employee details for this report.';
  static const employeeName = 'Employee Name';
  static const employeeNumber = 'Employee Number';
  static const department = 'Department';
  static const enterEmployeeName = 'Enter employee name';
  static const enterEmployeeNumber = 'Enter employee number';
  static const enterDepartment = 'Enter department';
  static const employeeNameRequired = 'Enter the employee name before continuing.';
  static const auto = 'Auto';
  static const observedEvent = 'Observed Event';
  static const observedEventNotice =
      'Be specific. Note hazards, equipment IDs, and immediate actions taken.';
  static const describeObservedEvent = 'Describe Observed Event';
  static const observedEventHint = 'Describe what you observed in detail...';
  static const eventRequired = 'Describe the observed event before continuing.';
  static const evidencePhotos = 'Evidence Photos';
  static const addPhoto = 'Add Photo';
  static const photosPending = 'Adding photos is being implemented.';
  static const potentialHazard = 'Potential Hazard';
  static const potentialHazardNotice =
      'Anticipate worst-case scenarios. Detail what could happen if no corrective action is taken.';
  static const describePotentialHazard = 'Describe Potential Hazard / Outcome';
  static const potentialHazardHint =
      'Describe the potential hazard, expected outcome, and possible impact...';
  static const hazardRequired = 'Describe the potential hazard before continuing.';
  static const actionTaken = 'Action Taken';
  static const actionTakenNotice =
      'Document immediate corrections & ongoing risk mitigations.';
  static const actionTakenLabel = 'Action Taken to Minimize Recurrence';
  static const actionTakenHint = 'Describe the immediate actions taken...';
  static const furtherActionsLabel = 'Further Action(s) Required';
  static const furtherActionsHint = 'Describe any additional actions needed...';
  static const actionRequired = 'Describe the action taken before continuing.';
  static const nextScreenPending = 'The next step is being implemented. Draft in memory:';
}
