import '../../features/observations/domain/observation_report.dart';

/// English copy is centralized so localization can be added without editing
/// individual widgets. This app has no server sync in version one.
abstract final class AppStrings {
  static const appName = 'Safety Observation';
  static const shortAppName = 'Safety Obs';
  static const subtitle = 'STOP CARD SYSTEM';
  static const offline = 'Offline';
  static const newObservation = 'New Observation';
  static const newObservationDescription =
      'File a real-time safety report or Stop Card instantly.';
  static const myReports = 'My Reports';
  static const myReportsDescription = 'View reports saved on this device';
  static const importReport = 'Import Report';
  static const importReportDescription = 'Import a .safety file';
  static const reportStatus = 'Report Status';
  static const activeSiteNotSet = 'NO ACTIVE SITE';
  static const drafts = 'Drafts';
  static const pending = 'Pending';
  static const completed = 'Completed';
  static const recent = 'Recent';
  static const offlineNotice =
      'Reports are saved on this device. Export a backup regularly to protect your data.';
  static const settings = 'Settings';
  static const myProfile = 'My Profile';
  static const saveProfile = 'Save Profile';
  static const profileSaved = 'Profile saved on this device.';
  static const backupTitle = 'Backup & Restore';
  static const backupExplanation = 'A backup includes all reports, photos, and signatures. Store the exported file in a secure location.';
  static const exportBackup = 'Export Backup';
  static const restoreBackup = 'Restore Backup';
  static const backupFailed = 'Unable to export backup.';
  static const restoreFailed = 'Unable to restore backup.';
  static String restoreCount(int count) => '$count reports restored.';
  static const reportImported = 'Report imported on this device.';
  static const reportAlreadyExists = 'This report is already on this device.';
  static const importFailed = 'Unable to import report.';
  static const pdfFailed = 'Unable to export PDF.';
  static const exportFailed = 'Unable to export report.';
  static const featurePending = 'This feature is being implemented.';
  static const selectObservationType = 'Select Observation Type';
  static const stepOneOfTen = 'Step 1 of 10';
  static const nearMiss = 'Near Miss';
  static const nearMissDescription =
      'An unplanned event that did not result in injury, illness, or damage.';
  static const tofs = 'TOFS';
  static const tofsDescription =
      'Time Out For Safety — brief discussion to address workplace safety.';
  static const hazardId = 'Hazard I.D.';
  static const hazardIdDescription =
      'Identification of potential sources of harm or adverse health effects.';
  static const stopCard = 'Stop Card';
  static const stopCardDescription =
      'Immediate authority to halt work due to unsafe conditions or actions.';
  static const stopCardCategory = 'Stop Card Category';
  static const positive = 'Positive';
  static const unsafeCorrective = 'Unsafe / Corrective';
  static const continueToForm = 'Continue to Form';
  static const selectCategory = 'Select a Stop Card category to continue.';
  static const basicInfo = 'Basic Info';
  static const stepTwoOfTen = 'Step 2 of 10';
  static const autoRecordedNotice =
      'Date, time, and report ID are recorded automatically.';
  static const reportId = 'Report ID';
  static const autoGenerated = 'Auto-generated';
  static const dateRecorded = 'Date Recorded';
  static const time = 'Time';
  static const area = 'Area';
  static const requiredAreaLabel = 'AREA *';
  static const selectArea = 'Select Area';
  static const enterArea = 'Enter work area';
  static const areaRequired = 'Select an area before continuing.';
  static const continueLabel = 'Continue';
  static const cancel = 'Cancel';
  static const save = 'Save';
  static const saveFailed = 'Unable to save the report. Please try again.';
  static const loadFailed = 'Unable to load reports. Please try again.';
  static const completeRequired = 'Complete the required report fields before finishing.';
  static const reportCompleted = 'Report completed and saved on this device.';
  static const draftSaved = 'Draft saved on this device.';
  static String stepOfTen(int step) => 'Step $step of 10';
  static const employeeInfo = 'Employee Info';
  static const employeeInfoNotice = 'Enter the employee details for this report.';
  static const employeeName = 'Employee Name';
  static const employeeNumber = 'Employee Number';
  static const department = 'Department';
  static const enterEmployeeName = 'Enter employee name';
  static const enterEmployeeNumber = 'Enter employee number';
  static const enterDepartment = 'Enter department';
  static const employeeNameRequired = 'Enter the employee name before continuing.';
  static const auto = 'Auto';
  static const observedEvent = 'Observed Event';
  static const observedEventNotice =
      'Be specific. Note hazards, equipment IDs, and immediate actions taken.';
  static const describeObservedEvent = 'Describe Observed Event';
  static const observedEventHint = 'Describe what you observed in detail...';
  static const eventRequired = 'Describe the observed event before continuing.';
  static const evidencePhotos = 'Evidence Photos';
  static const addPhoto = 'Add Photo';
  static const photosPending = 'Adding photos is being implemented.';
  static const photoFailed = 'Unable to add or remove photo. Please try again.';
  static const potentialHazard = 'Potential Hazard';
  static const potentialHazardNotice =
      'Anticipate worst-case scenarios. Detail what could happen if no corrective action is taken.';
  static const describePotentialHazard = 'Describe Potential Hazard / Outcome';
  static const potentialHazardHint =
      'Describe the potential hazard, expected outcome, and possible impact...';
  static const hazardRequired = 'Describe the potential hazard before continuing.';
  static const actionTaken = 'Action Taken';
  static const actionTakenNotice =
      'Document immediate corrections & ongoing risk mitigations.';
  static const actionTakenLabel = 'Action Taken to Minimize Recurrence';
  static const actionTakenHint = 'Describe the immediate actions taken...';
  static const furtherActionsLabel = 'Further Action(s) Required';
  static const furtherActionsHint = 'Describe any additional actions needed...';
  static const actionRequired = 'Describe the action taken before continuing.';
  static const nextScreenPending = 'The next step is being implemented. Draft in memory:';
  static const safetyCategories = 'Safety Categories';
  static const allCorrect = 'Observation All Correct';
  static const allCorrectHint = 'Mark all items below as safe and compliant.';
  static const safetyCategorySections = <String, List<String>>{
    'Reactions of People': [
      'Correcting Position of PPE', 'Moving or Changing Position',
      'Moving / Rearranging Work', 'Stopping Work or Task',
      'Connecting Earths / Grounds', 'Installing Isolations / Lockouts',
    ],
    'Personal Protective Equipment': [
      'Head Protection', 'Face & Eye Protection',
      'Ears / Hearing Protection', 'Respiratory System Protection',
      'Body Area Protection', 'Hand & Arm Protection',
      'Leg, Feet & Toe Protection',
    ],
    'People Positions': [
      'People Contact with Objects', 'Objects Striking People',
      'Body Part Trapped In / On / Between', 'People Falling',
      'Contact Extreme Temperature', 'Contact Electric Current',
      'Inhaling Hazardous Substance', 'Absorbing Hazardous Substance',
      'Swallowing Hazardous Substance', 'Straining / Overexertion',
      'Repetitive Similar Motion', 'Static Awkward Position / Posture',
    ],
    'Tools & Work Equipment': [
      'Incorrect for the Task / Job', 'Improper Use of Tools / Equipment',
      'Tools / Equipment Unsafe Condition',
    ],
    'Procedures & Orderliness': [
      'Inadequate for Work Being Done', 'Not Known or Not Understood',
      'Not Followed or Disregarded', 'Standard Orderliness Inadequate',
      'Standard Orderliness Not Known', 'Standard Orderliness Not Followed',
    ],
  };
  static const safeUnsafeActions = 'Safe / Unsafe Actions';
  static const safeUnsafeNotice =
      'Describe positive behaviors observed or immediate corrective actions taken.';
  static const encouragementLabel = 'Encouragement Given / Observed Safe Action';
  static const encouragementHint =
      'Example: Commended operator for an excellent pre-use inspection...';
  static const immediateCorrectionLabel =
      'Immediate Corrective Action / Observed Unsafe';
  static const immediateCorrectionHint =
      'Describe the unsafe act and the immediate correction...';
  static const safeUnsafeHint = 'Sections shown based on observation type.';
  static const riskRanking = 'Risk Ranking';
  static const riskNotice =
      'Evaluate the maximum potential consequence of the observed hazard if left unaddressed.';
  static const highRisk = 'HIGH RISK';
  static const mediumRisk = 'MEDIUM RISK';
  static const lowRisk = 'LOW RISK';
  static const highRiskDescription =
      'Imminent danger of severe injury, fatality, or major environmental incident. Requires immediate intervention.';
  static const mediumRiskDescription =
      'Potential for moderate injury, minor spill, or property damage. Needs correction within the shift.';
  static const lowRiskDescription =
      'Negligible hazard. Standard housekeeping issues or minor non-compliance items.';
  static const riskRequired = 'Select a risk ranking before continuing.';
  static const supervisor = 'Supervisor';
  static const supervisorNotified = 'Supervisor Notified?';
  static const yes = 'YES';
  static const no = 'NO';
  static const supervisorName = 'Supervisor Name';
  static const enterSupervisorName = 'Enter supervisor name';
  static const supervisorNameRequired = 'Enter supervisor name before continuing.';
  static const supervisorSignature = 'Supervisor Signature';
  static const signaturePending = 'Signature capture is being implemented.';
  static const tapToSign = 'Tap to sign';
  static const clear = 'Clear';
  static const supervisorNotes = 'Further Action / Notes';
  static const supervisorNotesHint = 'Enter recommended follow-up actions...';
  static const attachments = 'Attachments';
  static const uploadEvidencePhotos = 'Upload Evidence Photos';
  static String photosAttached(int count) => '$count PHOTOS ATTACHED';
  static const addMore = 'Add more';
  static const takePhoto = 'Take Photo';
  static const gallery = 'Gallery';
  static const reviewAndSave = 'Review & Save';
  static const completeReport = 'Complete Report';
  static const saveDraftOnly = 'Save Draft Only';
  static const storagePending = 'Saving on this device is being implemented.';
  static const selectedCategories = 'Selected Categories';
  static const type = 'Type';
  static String typeLabel(ObservationType type) => switch (type) {
    ObservationType.nearMiss => nearMiss,
    ObservationType.tofs => tofs,
    ObservationType.hazardId => hazardId,
    ObservationType.stopCard => stopCard,
  };
  static String riskLabel(RiskRanking risk) => switch (risk) {
    RiskRanking.high => highRisk,
    RiskRanking.medium => mediumRisk,
    RiskRanking.low => lowRisk,
  };
  static const searchReports = 'Search by ID, employee, area...';
  static const all = 'All';
  static const noReportsOnDevice =
      'No reports saved on this device yet. Start a new observation.';
  static const reportDetails = 'Report Details';
  static const edit = 'Edit';
  static const exportPdf = 'Export PDF';
  static const exportSafety = 'Export .safety file';
  static const duplicate = 'Duplicate';
  static const deleteReport = 'Delete Report';
  static const reportActionsPending = 'Report actions are being implemented.';
  static const deleteConfirm = 'Delete this report from this device? This cannot be undone.';
  static const deleteFailed = 'Unable to delete the report. Please try again.';
  static String statusLabel(ReportStatus status) => switch (status) {
    ReportStatus.draft => 'Draft',
    ReportStatus.ready => 'Ready',
    ReportStatus.sentForCompletion => 'Sent for completion',
    ReportStatus.received => 'Received',
    ReportStatus.inProgress => 'Pending',
    ReportStatus.completed => 'Completed',
    ReportStatus.exported => 'Exported',
  };
}
